### index.html 페이지
GET http://localhost:8080/index.html

### 회원가입 페이지
GET http://localhost:8080/user/form.html

### 회원가입
GET http://localhost:8080/user/create?userId=nio&password=password&name=최세환&email=sehan.choi@gmail.com

### 회원가입 POST
POST http://localhost:8080/user/create
Content-Type: application/x-www-form-urlencoded
Accept: */*

userId=nio&password=password&name=최세환&email=sehan.choi@gmail.com